update "order" set client_name = 'Fox iTunes' where code = 'ORDER01096';
update "order" set client_name = 'Fremantle' where code = 'ORDER00832';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00608';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00609';
update "order" set client_name = 'Lionsgate' where code = 'ORDER01030';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER01089';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00449';
update "order" set client_name = 'Warner Brothers iTunes' where code = 'ORDER00674';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER01136';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00381';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00380';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00383';
update "order" set client_name = 'Lionsgate' where code = 'ORDER00382';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00385';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00384';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00387';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00386';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00420';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00388';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00422';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00423';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00424';
update "order" set client_name = 'Fremantle' where code = 'ORDER00425';
update "order" set client_name = 'Neoclassic Film' where code = 'ORDER00426';
update "order" set client_name = 'Fremantle' where code = 'ORDER00427';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00543';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00542';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00012';
update "order" set client_name = 'Fox Mastering' where code = 'ORDER00015';
update "order" set client_name = 'Fox Mastering' where code = 'ORDER00014';
update "order" set client_name = 'Fox Samsung' where code = 'ORDER00017';
update "order" set client_name = 'Fremantle' where code = 'ORDER00544';
update "order" set client_name = 'Fox Esprit' where code = 'ORDER01013';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER01010';
update "order" set client_name = 'Disney' where code = 'ORDER01011';
update "order" set client_name = 'JetBlue' where code = 'ORDER01016';
update "order" set client_name = 'Lionsgate' where code = 'ORDER01017';
update "order" set client_name = 'Scripps Network' where code = 'ORDER01014';
update "order" set client_name = 'Fremantle' where code = 'ORDER01015';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00717';
update "order" set client_name = 'Fremantle' where code = 'ORDER00949';
update "order" set client_name = 'Disney' where code = 'ORDER00948';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00947';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00946';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00945';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00944';
update "order" set client_name = 'Summit' where code = 'ORDER00943';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00942';
update "order" set client_name = 'Fremantle' where code = 'ORDER00941';
update "order" set client_name = 'Fremantle' where code = 'ORDER00940';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER01031';
update "order" set client_name = 'Fox Latin America' where code = 'ORDER00226';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00876';
update "order" set client_name = 'Disney' where code = 'ORDER00440';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00441';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER01193';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00526';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00600';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00338';
update "order" set client_name = 'FX' where code = 'ORDER00339';
update "order" set client_name = 'Disney' where code = 'ORDER00334';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00335';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00336';
update "order" set client_name = 'Warner Brothers iTunes' where code = 'ORDER00337';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00330';
update "order" set client_name = 'Fremantle EST' where code = 'ORDER00331';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00332';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00333';
update "order" set client_name = 'Fremantle' where code = 'ORDER00911';
update "order" set client_name = 'Echostar' where code = 'ORDER00779';
update "order" set client_name = 'Fremantle' where code = 'ORDER00727';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00726';
update "order" set client_name = 'Lionsgate' where code = 'ORDER00831';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00830';
update "order" set client_name = 'Fremantle' where code = 'ORDER00837';
update "order" set client_name = 'Fox Latin America' where code = 'ORDER00836';
update "order" set client_name = 'Summit' where code = 'ORDER00835';
update "order" set client_name = 'Fox' where code = 'ORDER00704';
update "order" set client_name = 'Fox Latin America' where code = 'ORDER00932';
update "order" set client_name = 'Fremantle EST' where code = 'ORDER00933';
update "order" set client_name = 'Fremantle' where code = 'ORDER00839';
update "order" set client_name = 'Fremantle' where code = 'ORDER00838';
update "order" set client_name = 'Fox Latin America' where code = 'ORDER00936';
update "order" set client_name = 'Summit' where code = 'ORDER00937';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00934';
update "order" set client_name = 'ESPN' where code = 'ORDER00935';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01245';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00706';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01243';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01242';
update "order" set client_name = 'Fremantle' where code = 'ORDER00938';
update "order" set client_name = 'Fox Esprit' where code = 'ORDER00472';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER01126';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00701';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER01124';
update "order" set client_name = 'Fremantle' where code = 'ORDER01125';
update "order" set client_name = 'Fremantle EST' where code = 'ORDER01122';
update "order" set client_name = 'Fremantle EST' where code = 'ORDER00578';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01120';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00814';
update "order" set client_name = 'Fox Esprit' where code = 'ORDER00579';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00807';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00428';
update "order" set client_name = 'Disney' where code = 'ORDER00939';
update "order" set client_name = 'Fremantle' where code = 'ORDER01212';
update "order" set client_name = 'Fox Esprit' where code = 'ORDER00429';
update "order" set client_name = 'Fox Esprit' where code = 'ORDER00474';
update "order" set client_name = 'Fox Esprit' where code = 'ORDER00603';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00590';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00591';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00592';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00593';
update "order" set client_name = 'Scripps Network' where code = 'ORDER00594';
update "order" set client_name = 'Summit' where code = 'ORDER00595';
update "order" set client_name = 'Fox Telefonica' where code = 'ORDER00596';
update "order" set client_name = 'Lionsgate' where code = 'ORDER00597';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00598';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00612';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00611';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00610';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00617';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00616';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00615';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00614';
update "order" set client_name = 'Lionsgate' where code = 'ORDER00752';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00753';
update "order" set client_name = 'ESPN' where code = 'ORDER00750';
update "order" set client_name = 'Lionsgate' where code = 'ORDER00751';
update "order" set client_name = 'Disney' where code = 'ORDER00204';
update "order" set client_name = 'Paramount' where code = 'ORDER00757';
update "order" set client_name = 'Paramount' where code = 'ORDER00754';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00207';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00208';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00209';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00758';
update "order" set client_name = 'Fremantle' where code = 'ORDER00759';
update "order" set client_name = 'Warner Brothers iTunes' where code = 'ORDER01192';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER01232';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01233';
update "order" set client_name = 'Fremantle' where code = 'ORDER01230';
update "order" set client_name = 'Summit' where code = 'ORDER00845';
update "order" set client_name = 'Fremantle' where code = 'ORDER01236';
update "order" set client_name = 'FX' where code = 'ORDER01234';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00421';
update "order" set client_name = 'Fremantle' where code = 'ORDER01238';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01239';
update "order" set client_name = 'Fremantle' where code = 'ORDER01004';
update "order" set client_name = 'Fremantle File Duplication' where code = 'ORDER00183';
update "order" set client_name = 'Disney' where code = 'ORDER00182';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00181';
update "order" set client_name = 'Disney' where code = 'ORDER00180';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00187';
update "order" set client_name = 'FX' where code = 'ORDER00186';
update "order" set client_name = 'Fox Latin America' where code = 'ORDER00185';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00184';
update "order" set client_name = 'Fox Latin America' where code = 'ORDER00189';
update "order" set client_name = 'Max Post' where code = 'ORDER00188';
update "order" set client_name = 'Telenica - Nicaragua' where code = 'ORDER00448';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00920';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER01206';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00289';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER00059';
update "order" set client_name = 'FX' where code = 'ORDER00058';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00509';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00508';
update "order" set client_name = 'FX' where code = 'ORDER00055';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER00054';
update "order" set client_name = 'Fox Esprit' where code = 'ORDER00057';
update "order" set client_name = 'Lionsgate' where code = 'ORDER00056';
update "order" set client_name = 'JetBlue' where code = 'ORDER00051';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00050';
update "order" set client_name = 'Fox Playstation' where code = 'ORDER00053';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00500';
update "order" set client_name = 'Fox Esprit' where code = 'ORDER00114';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00115';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00116';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00117';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00110';
update "order" set client_name = 'Lionsgate' where code = 'ORDER00111';
update "order" set client_name = 'Lionsgate' where code = 'ORDER00112';
update "order" set client_name = 'Fox Esprit' where code = 'ORDER00113';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER00297';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER00296';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER00295';
update "order" set client_name = 'Fremantle' where code = 'ORDER00926';
update "order" set client_name = 'Fox Playstation' where code = 'ORDER00293';
update "order" set client_name = 'Paramount' where code = 'ORDER00119';
update "order" set client_name = 'Disney' where code = 'ORDER00291';
update "order" set client_name = 'Fremantle' where code = 'ORDER00546';
update "order" set client_name = 'Summit' where code = 'ORDER00545';
update "order" set client_name = 'Fremantle' where code = 'ORDER01143';
update "order" set client_name = 'Fox Telefonica' where code = 'ORDER00988';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00731';
update "order" set client_name = 'Disney' where code = 'ORDER01012';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00018';
update "order" set client_name = 'Summit' where code = 'ORDER00549';
update "order" set client_name = 'Fox Mastering' where code = 'ORDER01009';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER01138';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00378';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00379';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER00548';
update "order" set client_name = 'Fox Esprit' where code = 'ORDER00974';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00370';
update "order" set client_name = 'Lionsgate' where code = 'ORDER00371';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00372';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00373';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00374';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00375';
update "order" set client_name = 'Lionsgate' where code = 'ORDER00377';
update "order" set client_name = 'Fox Esprit' where code = 'ORDER00473';
update "order" set client_name = 'Lionsgate' where code = 'ORDER00046';
update "order" set client_name = 'Fox Esprit' where code = 'ORDER00471';
update "order" set client_name = 'Fox Esprit' where code = 'ORDER00470';
update "order" set client_name = 'Fox Esprit' where code = 'ORDER00477';
update "order" set client_name = 'Fox Esprit' where code = 'ORDER00476';
update "order" set client_name = 'Fox Esprit' where code = 'ORDER00475';
update "order" set client_name = 'Fox Latin America' where code = 'ORDER00511';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00572';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00573';
update "order" set client_name = 'Fox Esprit' where code = 'ORDER00479';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00571';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER00576';
update "order" set client_name = 'Fremantle' where code = 'ORDER00577';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00574';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00575';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER01241';
update "order" set client_name = 'Warner Brothers iTunes' where code = 'ORDER00045';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00879';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00878';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00877';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00514';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00875';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00874';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00873';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00872';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00871';
update "order" set client_name = 'Fremantle' where code = 'ORDER00870';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00976';
update "order" set client_name = 'Fremantle' where code = 'ORDER00977';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00975';
update "order" set client_name = 'Fox Mastering' where code = 'ORDER00972';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00516';
update "order" set client_name = 'Summit' where code = 'ORDER00970';
update "order" set client_name = 'Fox Playstation' where code = 'ORDER00971';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00517';
update "order" set client_name = 'Fox Playstation' where code = 'ORDER00978';
update "order" set client_name = 'Fremantle' where code = 'ORDER00979';
update "order" set client_name = 'Disney' where code = 'ORDER00288';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00707';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01022';
update "order" set client_name = 'Warner Brothers iTunes' where code = 'ORDER01021';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00989';
update "order" set client_name = 'Warner Brothers iTunes' where code = 'ORDER01020';
update "order" set client_name = 'Fremantle' where code = 'ORDER00906';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00983';
update "order" set client_name = 'Fremantle' where code = 'ORDER00982';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00981';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00980';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00987';
update "order" set client_name = 'Lionsgate' where code = 'ORDER00986';
update "order" set client_name = 'Lionsgate' where code = 'ORDER00985';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER00984';
update "order" set client_name = 'Fox Telefonica' where code = 'ORDER01095';
update "order" set client_name = 'Warner Brothers iTunes' where code = 'ORDER01025';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00698';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01046';
update "order" set client_name = 'Warner Brothers iTunes' where code = 'ORDER01024';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00657';
update "order" set client_name = 'Lionsgate' where code = 'ORDER00280';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00808';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00809';
update "order" set client_name = 'Fremantle' where code = 'ORDER00653';
update "order" set client_name = 'Fox Duplication' where code = 'ORDER00652';
update "order" set client_name = 'Fremantle' where code = 'ORDER00651';
update "order" set client_name = 'Lionsgate' where code = 'ORDER00281';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00802';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER00803';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00800';
update "order" set client_name = 'Fox Latin America' where code = 'ORDER00801';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00806';
update "order" set client_name = 'Lionsgate' where code = 'ORDER00282';
update "order" set client_name = 'Scripps Network' where code = 'ORDER00804';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00658';
update "order" set client_name = 'Warner Brothers iTunes' where code = 'ORDER01028';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00179';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01171';
update "order" set client_name = 'Disney' where code = 'ORDER01170';
update "order" set client_name = 'Fremantle' where code = 'ORDER01173';
update "order" set client_name = 'Fremantle' where code = 'ORDER01172';
update "order" set client_name = 'Fox Belgacom' where code = 'ORDER01008';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01174';
update "order" set client_name = 'Fremantle' where code = 'ORDER01177';
update "order" set client_name = 'Fremantle' where code = 'ORDER01176';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01179';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01178';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER01072';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00540';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER01073';
update "order" set client_name = 'Fox Mastering' where code = 'ORDER01074';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER01075';
update "order" set client_name = 'Summit' where code = 'ORDER00997';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00170';
update "order" set client_name = 'Fox Mastering' where code = 'ORDER00078';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00570';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER00547';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER00150';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00151';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00259';
update "order" set client_name = 'Fox Mastering' where code = 'ORDER00153';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00154';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00155';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00156';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER00157';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00158';
update "order" set client_name = 'Max Post' where code = 'ORDER00159';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00251';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00250';
update "order" set client_name = 'Fox Mastering' where code = 'ORDER00257';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00256';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00255';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00254';
update "order" set client_name = 'Scripps Network' where code = 'ORDER00785';
update "order" set client_name = 'DirecTV' where code = 'ORDER00787';
update "order" set client_name = 'DirecTV' where code = 'ORDER00786';
update "order" set client_name = 'Echostar' where code = 'ORDER00781';
update "order" set client_name = 'Echostar' where code = 'ORDER00780';
update "order" set client_name = 'Scripps Network' where code = 'ORDER00783';
update "order" set client_name = 'ESPN' where code = 'ORDER00782';
update "order" set client_name = 'Lionsgate' where code = 'ORDER01231';
update "order" set client_name = 'DirecTV' where code = 'ORDER00789';
update "order" set client_name = 'DirecTV' where code = 'ORDER00788';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01081';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00253';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00633';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00632';
update "order" set client_name = 'Fox Esprit' where code = 'ORDER00635';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01097';
update "order" set client_name = 'Strand Releasing' where code = 'ORDER01084';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01116';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00589';
update "order" set client_name = 'Fox' where code = 'ORDER00141';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00439';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00438';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00437';
update "order" set client_name = 'Fremantle' where code = 'ORDER01061';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00435';
update "order" set client_name = 'Fox' where code = 'ORDER00140';
update "order" set client_name = 'Lionsgate' where code = 'ORDER00433';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00432';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00431';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00430';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00024';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00537';
update "order" set client_name = 'Fremantle SAN Package' where code = 'ORDER00026';
update "order" set client_name = 'A and E' where code = 'ORDER00027';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00532';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00533';
update "order" set client_name = 'Fremantle EST' where code = 'ORDER00022';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER00023';
update "order" set client_name = 'Fremantle' where code = 'ORDER01001';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01000';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER01003';
update "order" set client_name = 'Summit' where code = 'ORDER01002';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER01005';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00029';
update "order" set client_name = 'Lionsgate' where code = 'ORDER00538';
update "order" set client_name = 'Fox Latin America' where code = 'ORDER00539';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00588';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00581';
update "order" set client_name = 'Fox Latin America' where code = 'ORDER00630';
update "order" set client_name = 'Echostar' where code = 'ORDER00580';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01121';
update "order" set client_name = 'Fremantle EST' where code = 'ORDER01099';
update "order" set client_name = 'Fremantle' where code = 'ORDER01092';
update "order" set client_name = 'Disney' where code = 'ORDER00149';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER01088';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00221';
update "order" set client_name = 'Summit' where code = 'ORDER00205';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00360';
update "order" set client_name = 'Fremantle' where code = 'ORDER00663';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER00323';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00322';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00321';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00320';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER00326';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER00325';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER00324';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00442';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00443';
update "order" set client_name = 'Fox Esprit' where code = 'ORDER00329';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00328';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00446';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00447';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00444';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00445';
update "order" set client_name = 'Summit' where code = 'ORDER00206';
update "order" set client_name = 'Fox Mastering' where code = 'ORDER01077';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00216';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01217';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00215';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00846';
update "order" set client_name = 'Warner Brothers iTunes' where code = 'ORDER00847';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00844';
update "order" set client_name = 'Fox Samsung' where code = 'ORDER00742';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00842';
update "order" set client_name = 'Summit' where code = 'ORDER00843';
update "order" set client_name = 'Fremantle' where code = 'ORDER00840';
update "order" set client_name = 'Fremantle' where code = 'ORDER00841';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00921';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00745';
update "order" set client_name = 'Fremantle' where code = 'ORDER00923';
update "order" set client_name = 'Warner Brothers iTunes' where code = 'ORDER00922';
update "order" set client_name = 'Fremantle' where code = 'ORDER00925';
update "order" set client_name = 'Disney' where code = 'ORDER00924';
update "order" set client_name = 'Warner Brothers iTunes' where code = 'ORDER00848';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00744';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER01198';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER01139';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00211';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00656';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER01135';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER01134';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER01137';
update "order" set client_name = 'Showtime Networks' where code = 'ORDER00746';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01131';
update "order" set client_name = 'Fremantle' where code = 'ORDER00655';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER01133';
update "order" set client_name = 'Fremantle' where code = 'ORDER01132';
update "order" set client_name = 'Fremantle' where code = 'ORDER00654';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01040';
update "order" set client_name = 'Fox Mastering' where code = 'ORDER01082';
update "order" set client_name = 'Summit' where code = 'ORDER00692';
update "order" set client_name = 'Fox Amazon' where code = 'ORDER00634';
update "order" set client_name = 'Summit' where code = 'ORDER00718';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER00650';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00587';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00586';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00585';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00584';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00583';
update "order" set client_name = 'Warner Brothers iTunes' where code = 'ORDER00582';
update "order" set client_name = 'Scripps Network' where code = 'ORDER00668';
update "order" set client_name = 'Scripps Network' where code = 'ORDER00669';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER00666';
update "order" set client_name = 'Warner Brothers iTunes' where code = 'ORDER00667';
update "order" set client_name = 'Summit' where code = 'ORDER00662';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER00637';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00660';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00217';
update "order" set client_name = 'Lionsgate' where code = 'ORDER00740';
update "order" set client_name = 'ESPN' where code = 'ORDER00743';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00214';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00213';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00212';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00747';
update "order" set client_name = 'Paramount' where code = 'ORDER00210';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00749';
update "order" set client_name = 'Fox Samsung' where code = 'ORDER00748';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00929';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00219';
update "order" set client_name = 'Fox Esprit' where code = 'ORDER00218';
update "order" set client_name = 'Fremantle' where code = 'ORDER01221';
update "order" set client_name = 'Santa Monica Video' where code = 'ORDER01220';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01223';
update "order" set client_name = 'Fremantle' where code = 'ORDER01222';
update "order" set client_name = 'Quality Films' where code = 'ORDER01225';
update "order" set client_name = 'Summit' where code = 'ORDER01227';
update "order" set client_name = 'Mar Vista' where code = 'ORDER00690';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01229';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01228';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01182';
update "order" set client_name = 'JetBlue' where code = 'ORDER00805';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01184';
update "order" set client_name = 'Fremantle' where code = 'ORDER00910';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01186';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00340';
update "order" set client_name = 'Santa Monica Video' where code = 'ORDER01085';
update "order" set client_name = 'Lionsgate EST/VOD' where code = 'ORDER00719';
update "order" set client_name = 'Quality Films' where code = 'ORDER01226';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01053';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01180';
update "order" set client_name = 'Fox' where code = 'ORDER00697';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01181';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER01194';
update "order" set client_name = 'Summit' where code = 'ORDER00833';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00062';
update "order" set client_name = 'FX' where code = 'ORDER00108';
update "order" set client_name = 'FX' where code = 'ORDER00064';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00725';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00067';
update "order" set client_name = 'Max Post' where code = 'ORDER00103';
update "order" set client_name = 'Fox Esprit' where code = 'ORDER00102';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00101';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00100';
update "order" set client_name = 'FX' where code = 'ORDER00107';
update "order" set client_name = 'FX' where code = 'ORDER00106';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00105';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00104';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00262';
update "order" set client_name = 'Fremantle EST' where code = 'ORDER00263';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00260';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00261';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00266';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00267';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00264';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00265';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00723';
update "order" set client_name = 'Summit' where code = 'ORDER00268';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00269';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01049';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01048';
update "order" set client_name = 'Fremantle' where code = 'ORDER00722';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER00088';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00089';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00724';
update "order" set client_name = 'Fremantle' where code = 'ORDER00721';
update "order" set client_name = 'Apple' where code = 'ORDER00083';
update "order" set client_name = 'Fox Latin America' where code = 'ORDER00834';
update "order" set client_name = 'Fox Esprit' where code = 'ORDER00086';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00087';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00084';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER00085';
update "order" set client_name = 'Fox Amazon' where code = 'ORDER00695';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER01058';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01183';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00659';
update "order" set client_name = 'Fremantle EST' where code = 'ORDER00930';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00507';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00741';
update "order" set client_name = 'Scripps Network' where code = 'ORDER00714';
update "order" set client_name = 'Warner Brothers iTunes' where code = 'ORDER01026';
update "order" set client_name = 'Fox Latin America' where code = 'ORDER00931';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00369';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00367';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00366';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00365';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00364';
update "order" set client_name = 'Warner Brothers iTunes' where code = 'ORDER00363';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00361';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00694';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00406';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00568';
update "order" set client_name = 'Fremantle' where code = 'ORDER00404';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00405';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00402';
update "order" set client_name = 'Fremantle' where code = 'ORDER00403';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00400';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00401';
update "order" set client_name = 'Fremantle' where code = 'ORDER00561';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00558';
update "order" set client_name = 'Fremantle' where code = 'ORDER00563';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00562';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00565';
update "order" set client_name = 'Fremantle' where code = 'ORDER00564';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00408';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00409';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00882';
update "order" set client_name = 'Warner Brothers iTunes' where code = 'ORDER00883';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00880';
update "order" set client_name = 'Summit' where code = 'ORDER00863';
update "order" set client_name = 'Fremantle' where code = 'ORDER00887';
update "order" set client_name = 'Fremantle' where code = 'ORDER00884';
update "order" set client_name = 'Fremantle' where code = 'ORDER00885';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER00888';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER00889';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00965';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00964';
update "order" set client_name = 'Fremantle EST' where code = 'ORDER00967';
update "order" set client_name = 'Fremantle' where code = 'ORDER00966';
update "order" set client_name = 'Fox Esprit' where code = 'ORDER00961';
update "order" set client_name = 'Fox Esprit' where code = 'ORDER00960';
update "order" set client_name = 'Fox Playstation' where code = 'ORDER00963';
update "order" set client_name = 'Fremantle' where code = 'ORDER00962';
update "order" set client_name = 'Well Go' where code = 'ORDER00968';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01050';
update "order" set client_name = 'Warner Brothers iTunes' where code = 'ORDER01018';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00348';
update "order" set client_name = 'Fox Samsung' where code = 'ORDER00520';
update "order" set client_name = 'Warner Brothers iTunes' where code = 'ORDER01240';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00418';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00318';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00319';
update "order" set client_name = 'Summit' where code = 'ORDER01127';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00312';
update "order" set client_name = 'Paramount' where code = 'ORDER00313';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00310';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00311';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00316';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00317';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00314';
update "order" set client_name = 'Disney' where code = 'ORDER00315';
update "order" set client_name = 'Warner Brothers iTunes' where code = 'ORDER01019';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00618';
update "order" set client_name = 'Fremantle' where code = 'ORDER01080';
update "order" set client_name = 'Fremantle' where code = 'ORDER01123';
update "order" set client_name = 'Fremantle' where code = 'ORDER00819';
update "order" set client_name = 'Warner Brothers iTunes' where code = 'ORDER00818';
update "order" set client_name = 'Fremantle' where code = 'ORDER00892';
update "order" set client_name = 'Fox' where code = 'ORDER00709';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00708';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00810';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00813';
update "order" set client_name = 'Summit' where code = 'ORDER00812';
update "order" set client_name = 'Fox' where code = 'ORDER00815';
update "order" set client_name = 'Apple' where code = 'ORDER00700';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00703';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER01037';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00525';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER01070';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00524';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00527';
update "order" set client_name = 'Fremantle' where code = 'ORDER01144';
update "order" set client_name = 'Summit' where code = 'ORDER00899';
update "order" set client_name = 'Fremantle EST' where code = 'ORDER01146';
update "order" set client_name = 'Fremantle EST' where code = 'ORDER01147';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER01140';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER01141';
update "order" set client_name = 'Fremantle' where code = 'ORDER01142';
update "order" set client_name = 'Fremantle' where code = 'ORDER00898';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER01038';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00599';
update "order" set client_name = 'Fremantle EST' where code = 'ORDER01148';
update "order" set client_name = 'Fremantle EST' where code = 'ORDER01149';
update "order" set client_name = 'Fremantle' where code = 'ORDER00689';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER01071';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00953';
update "order" set client_name = 'Lionsgate' where code = 'ORDER00523';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00460';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER00522';
update "order" set client_name = 'Disney' where code = 'ORDER00109';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER01034';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER00063';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER01035';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00686';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00631';
update "order" set client_name = 'FX' where code = 'ORDER00146';
update "order" set client_name = 'Lionsgate' where code = 'ORDER00145';
update "order" set client_name = 'Lionsgate' where code = 'ORDER00144';
update "order" set client_name = 'Fox Playstation' where code = 'ORDER00143';
update "order" set client_name = 'Paramount' where code = 'ORDER00142';
update "order" set client_name = 'Fox Playstation' where code = 'ORDER00228';
update "order" set client_name = 'Buena Vista International' where code = 'ORDER00229';
update "order" set client_name = 'Summit' where code = 'ORDER00639';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00227';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00224';
update "order" set client_name = 'Max Post' where code = 'ORDER00225';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00222';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00223';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00220';
update "order" set client_name = 'Disney' where code = 'ORDER00148';
update "order" set client_name = 'Lionsgate' where code = 'ORDER01032';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01051';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER01033';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER01188';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01052';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01224';
update "order" set client_name = 'Warner Brothers iTunes' where code = 'ORDER01189';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER01045';
update "order" set client_name = 'Fremantle SAN Package' where code = 'ORDER00039';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00038';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER01044';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00033';
update "order" set client_name = 'Well Go' where code = 'ORDER00032';
update "order" set client_name = 'A and E' where code = 'ORDER00031';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER00030';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00037';
update "order" set client_name = 'Fremantle SAN Package' where code = 'ORDER00036';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00035';
update "order" set client_name = 'Strand Releasing' where code = 'ORDER00034';
update "order" set client_name = 'Fox Telefonica' where code = 'ORDER00132';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00133';
update "order" set client_name = 'FX' where code = 'ORDER00130';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00131';
update "order" set client_name = 'FX' where code = 'ORDER00136';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00137';
update "order" set client_name = 'Disney' where code = 'ORDER00134';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00135';
update "order" set client_name = 'Summit' where code = 'ORDER00684';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01041';
update "order" set client_name = 'Mar Vista' where code = 'ORDER00138';
update "order" set client_name = 'Disney' where code = 'ORDER00139';
update "order" set client_name = 'Summit' where code = 'ORDER00680';
update "order" set client_name = 'Entertainment One' where code = 'ORDER00681';
update "order" set client_name = 'Summit' where code = 'ORDER00682';
update "order" set client_name = 'Fox Belgacom' where code = 'ORDER00683';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01185';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00622';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01043';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00623';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00505';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01042';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00620';
update "order" set client_name = 'Summit' where code = 'ORDER00729';
update "order" set client_name = 'FX' where code = 'ORDER01235';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00530';
update "order" set client_name = 'Lionsgate' where code = 'ORDER00258';
update "order" set client_name = 'Warner Brothers iTunes' where code = 'ORDER01027';
update "order" set client_name = 'Fremantle' where code = 'ORDER01076';
update "order" set client_name = 'Fox Latin America' where code = 'ORDER00626';
update "order" set client_name = 'Paramount' where code = 'ORDER01129';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00627';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00624';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00559';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00625';
update "order" set client_name = 'Fremantle' where code = 'ORDER00728';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00619';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00356';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00458';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00354';
update "order" set client_name = 'Disney' where code = 'ORDER00355';
update "order" set client_name = 'Lionsgate' where code = 'ORDER00352';
update "order" set client_name = 'Lionsgate' where code = 'ORDER00353';
update "order" set client_name = 'FX' where code = 'ORDER00350';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00252';
update "order" set client_name = 'Fox Belgacom' where code = 'ORDER00451';
update "order" set client_name = 'Telenica - Nicaragua' where code = 'ORDER00450';
update "order" set client_name = 'Televisa' where code = 'ORDER00453';
update "order" set client_name = 'Fox Esprit' where code = 'ORDER00452';
update "order" set client_name = 'Fremantle' where code = 'ORDER00455';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00454';
update "order" set client_name = 'Lionsgate' where code = 'ORDER00457';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00359';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00629';
update "order" set client_name = 'Fox Latin America' where code = 'ORDER00855';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00613';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00857';
update "order" set client_name = 'Scripps Network' where code = 'ORDER00856';
update "order" set client_name = 'Warner Brothers iTunes' where code = 'ORDER00918';
update "order" set client_name = 'Empire Distribution' where code = 'ORDER00919';
update "order" set client_name = 'Fremantle' where code = 'ORDER00853';
update "order" set client_name = 'Fremantle' where code = 'ORDER00852';
update "order" set client_name = 'Fremantle' where code = 'ORDER00914';
update "order" set client_name = 'Fremantle' where code = 'ORDER00915';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00916';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00917';
update "order" set client_name = 'Lionsgate' where code = 'ORDER00859';
update "order" set client_name = 'Fox Playstation' where code = 'ORDER00858';
update "order" set client_name = 'Fremantle' where code = 'ORDER00912';
update "order" set client_name = 'Fremantle' where code = 'ORDER00913';
update "order" set client_name = 'Fremantle' where code = 'ORDER01100';
update "order" set client_name = 'Fox Esprit' where code = 'ORDER00636';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01102';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER01103';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER01104';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER01105';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER01106';
update "order" set client_name = 'Fremantle' where code = 'ORDER01107';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER01108';
update "order" set client_name = 'Fremantle' where code = 'ORDER01109';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00621';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00973';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00200';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00521';
update "order" set client_name = 'Fremantle' where code = 'ORDER01128';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00201';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER00202';
update "order" set client_name = 'Fox Esprit' where code = 'ORDER00478';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER00203';
update "order" set client_name = 'Lionsgate EST/VOD' where code = 'ORDER00679';
update "order" set client_name = 'Lionsgate' where code = 'ORDER00675';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00756';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00677';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00676';
update "order" set client_name = 'Warner Brothers iTunes' where code = 'ORDER00671';
update "order" set client_name = 'Scripps Network' where code = 'ORDER00670';
update "order" set client_name = 'Scripps Network' where code = 'ORDER00673';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00557';
update "order" set client_name = 'Disney' where code = 'ORDER00774';
update "order" set client_name = 'Summit' where code = 'ORDER00775';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00776';
update "order" set client_name = 'Scripps Network' where code = 'ORDER00777';
update "order" set client_name = 'Video Services Corp' where code = 'ORDER00770';
update "order" set client_name = 'Video Services Corp' where code = 'ORDER00771';
update "order" set client_name = 'Lionsgate' where code = 'ORDER00772';
update "order" set client_name = 'Lionsgate' where code = 'ORDER00773';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00541';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00755';
update "order" set client_name = 'Scripps Network' where code = 'ORDER00778';
update "order" set client_name = 'Fox Telefonica' where code = 'ORDER00642';
update "order" set client_name = 'Fremantle' where code = 'ORDER01214';
update "order" set client_name = 'Fremantle' where code = 'ORDER01215';
update "order" set client_name = 'Fox Playstation' where code = 'ORDER01216';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00643';
update "order" set client_name = 'Fremantle' where code = 'ORDER01210';
update "order" set client_name = 'Fremantle' where code = 'ORDER01211';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER01199';
update "order" set client_name = 'Fremantle' where code = 'ORDER01213';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER01197';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER01196';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER01195';
update "order" set client_name = 'Fox Esprit' where code = 'ORDER00306';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01218';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01219';
update "order" set client_name = 'Warner Brothers iTunes' where code = 'ORDER01191';
update "order" set client_name = 'Warner Brothers iTunes' where code = 'ORDER01190';
update "order" set client_name = 'Fox Mastering' where code = 'ORDER01029';
update "order" set client_name = 'Fremantle' where code = 'ORDER00648';
update "order" set client_name = 'Fremantle' where code = 'ORDER00691';
update "order" set client_name = 'Fremantle EST' where code = 'ORDER00488';
update "order" set client_name = 'Fremantle EST' where code = 'ORDER00489';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00486';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00487';
update "order" set client_name = 'Echostar' where code = 'ORDER00484';
update "order" set client_name = 'Summit' where code = 'ORDER00485';
update "order" set client_name = 'Summit' where code = 'ORDER00482';
update "order" set client_name = 'Summit' where code = 'ORDER00483';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00480';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00481';
update "order" set client_name = 'Fremantle' where code = 'ORDER01078';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER01079';
update "order" set client_name = 'A and E' where code = 'ORDER00073';
update "order" set client_name = 'Fox Esprit' where code = 'ORDER00072';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00178';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER00070';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00176';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00177';
update "order" set client_name = 'Lionsgate' where code = 'ORDER00174';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00175';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00172';
update "order" set client_name = 'Disney' where code = 'ORDER00173';
update "order" set client_name = 'Fox Mastering' where code = 'ORDER00079';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00171';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00271';
update "order" set client_name = 'Buena Vista International' where code = 'ORDER00270';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER00273';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00272';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00275';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00274';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00277';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00276';
update "order" set client_name = 'Disney' where code = 'ORDER00279';
update "order" set client_name = 'Fremantle' where code = 'ORDER00278';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00099';
update "order" set client_name = 'Disney' where code = 'ORDER00098';
update "order" set client_name = 'Fremantle' where code = 'ORDER00688';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00811';
update "order" set client_name = 'Well Go' where code = 'ORDER00091';
update "order" set client_name = 'Strand Releasing' where code = 'ORDER00090';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00093';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00092';
update "order" set client_name = 'FX' where code = 'ORDER00095';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00094';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00097';
update "order" set client_name = 'Fremantle File Duplication' where code = 'ORDER00096';
update "order" set client_name = 'Fremantle EST' where code = 'ORDER01145';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00392';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00393';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00390';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00391';
update "order" set client_name = 'Summit' where code = 'ORDER00396';
update "order" set client_name = 'Summit' where code = 'ORDER00397';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00394';
update "order" set client_name = 'Summit' where code = 'ORDER00395';
update "order" set client_name = 'Summit' where code = 'ORDER00398';
update "order" set client_name = 'Summit' where code = 'ORDER00399';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00415';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00414';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00417';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00416';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00411';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00410';
update "order" set client_name = 'Fremantle' where code = 'ORDER00413';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00412';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00554';
update "order" set client_name = 'Fremantle' where code = 'ORDER00555';
update "order" set client_name = 'Summit' where code = 'ORDER00556';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00456';
update "order" set client_name = 'Summit' where code = 'ORDER00550';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00551';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00552';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00553';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00958';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00959';
update "order" set client_name = 'Disney' where code = 'ORDER00893';
update "order" set client_name = 'Fremantle' where code = 'ORDER00628';
update "order" set client_name = 'Fremantle' where code = 'ORDER00895';
update "order" set client_name = 'FX' where code = 'ORDER00894';
update "order" set client_name = 'Fremantle' where code = 'ORDER00897';
update "order" set client_name = 'Fremantle' where code = 'ORDER00896';
update "order" set client_name = 'Baker Productions LLC' where code = 'ORDER00950';
update "order" set client_name = 'Baker Productions LLC' where code = 'ORDER00951';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00952';
update "order" set client_name = 'Lionsgate' where code = 'ORDER00737';
update "order" set client_name = 'Baker Productions LLC' where code = 'ORDER00954';
update "order" set client_name = 'Baker Productions LLC' where code = 'ORDER00955';
update "order" set client_name = 'Disney' where code = 'ORDER00956';
update "order" set client_name = 'Fox Samsung' where code = 'ORDER00957';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00734';
update "order" set client_name = 'Fremantle' where code = 'ORDER00824';
update "order" set client_name = 'Scripps Network' where code = 'ORDER00716';
update "order" set client_name = 'Fremantle' where code = 'ORDER00825';
update "order" set client_name = 'Fremantle' where code = 'ORDER00928';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01204';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00569';
update "order" set client_name = 'Fox Latin America' where code = 'ORDER00685';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER00407';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00735';
update "order" set client_name = 'Showtime Networks' where code = 'ORDER00309';
update "order" set client_name = 'ESPN' where code = 'ORDER00308';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00529';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER00301';
update "order" set client_name = 'Showtime Networks' where code = 'ORDER00300';
update "order" set client_name = 'Showtime Networks' where code = 'ORDER00303';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER00302';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00305';
update "order" set client_name = 'Showtime Networks' where code = 'ORDER00304';
update "order" set client_name = 'Disney' where code = 'ORDER00307';
update "order" set client_name = 'Fremantle' where code = 'ORDER00849';
update "order" set client_name = 'Summit' where code = 'ORDER01187';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00638';
update "order" set client_name = 'Fremantle' where code = 'ORDER00730';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00528';
update "order" set client_name = 'Lionsgate' where code = 'ORDER00732';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00733';
update "order" set client_name = 'Fox Esprit' where code = 'ORDER00828';
update "order" set client_name = 'Fox Mastering' where code = 'ORDER00829';
update "order" set client_name = 'Fox Playstation' where code = 'ORDER00736';
update "order" set client_name = 'A and E' where code = 'ORDER00560';
update "order" set client_name = 'Lionsgate' where code = 'ORDER00738';
update "order" set client_name = 'Lionsgate' where code = 'ORDER00739';
update "order" set client_name = 'Fox Latin America' where code = 'ORDER00826';
update "order" set client_name = 'Fox Esprit' where code = 'ORDER00827';
update "order" set client_name = 'Fremantle' where code = 'ORDER00820';
update "order" set client_name = 'Fremantle' where code = 'ORDER00821';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00822';
update "order" set client_name = 'Fremantle' where code = 'ORDER00823';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER01159';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER01158';
update "order" set client_name = 'Fox Esprit' where code = 'ORDER00854';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01153';
update "order" set client_name = 'Fremantle' where code = 'ORDER01152';
update "order" set client_name = 'Fremantle' where code = 'ORDER01151';
update "order" set client_name = 'Fremantle' where code = 'ORDER01150';
update "order" set client_name = 'Fremantle' where code = 'ORDER01157';
update "order" set client_name = 'Fremantle' where code = 'ORDER01156';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER01155';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01154';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00358';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00567';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00436';
update "order" set client_name = 'Fox Latin America' where code = 'ORDER00851';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER01175';
update "order" set client_name = 'Fox Esprit' where code = 'ORDER00566';
update "order" set client_name = 'Fox Mastering' where code = 'ORDER00850';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00434';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER00881';
update "order" set client_name = 'Echostar' where code = 'ORDER00687';
update "order" set client_name = 'Fremantle' where code = 'ORDER01098';
update "order" set client_name = 'Summit' where code = 'ORDER00604';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00536';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00606';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00607';
update "order" set client_name = 'Summit' where code = 'ORDER00239';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER00238';
update "order" set client_name = 'Fox Esprit' where code = 'ORDER01093';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER00025';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER00235';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00234';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER00237';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00236';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00231';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00230';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00233';
update "order" set client_name = 'Scripps Network' where code = 'ORDER00232';
update "order" set client_name = 'Fremantle' where code = 'ORDER01086';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER01091';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00535';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00198';
update "order" set client_name = 'Fox Samsung' where code = 'ORDER00199';
update "order" set client_name = 'Fremantle EST' where code = 'ORDER01101';
update "order" set client_name = 'Summit' where code = 'ORDER00194';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00195';
update "order" set client_name = 'Fox Playstation' where code = 'ORDER00196';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER00197';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00190';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00191';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00192';
update "order" set client_name = 'Fox Esprit' where code = 'ORDER00193';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER01161';
update "order" set client_name = 'Warner Brothers iTunes' where code = 'ORDER01090';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER00294';
update "order" set client_name = 'Paramount' where code = 'ORDER00121';
update "order" set client_name = 'Fox Samsung' where code = 'ORDER00518';
update "order" set client_name = 'Fox Playstation' where code = 'ORDER00519';
update "order" set client_name = 'Fremantle' where code = 'ORDER01006';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01036';
update "order" set client_name = 'Fremantle File Duplication' where code = 'ORDER00048';
update "order" set client_name = 'Max Post' where code = 'ORDER00049';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00510';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER00028';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER00512';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00513';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00042';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00515';
update "order" set client_name = 'Strand Releasing' where code = 'ORDER00040';
update "order" set client_name = 'Quality Films' where code = 'ORDER00041';
update "order" set client_name = 'Warner Brothers iTunes' where code = 'ORDER01023';
update "order" set client_name = 'Paramount' where code = 'ORDER00120';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00123';
update "order" set client_name = 'Paramount' where code = 'ORDER00122';
update "order" set client_name = 'Lit Post' where code = 'ORDER00125';
update "order" set client_name = 'Shout Factory' where code = 'ORDER00124';
update "order" set client_name = 'Fremantle File Duplication' where code = 'ORDER00127';
update "order" set client_name = 'Fox' where code = 'ORDER00126';
update "order" set client_name = 'Paramount' where code = 'ORDER00129';
update "order" set client_name = 'Paramount' where code = 'ORDER00128';
update "order" set client_name = 'Summit' where code = 'ORDER00699';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00283';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00284';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00285';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00286';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00287';
update "order" set client_name = 'ESPN' where code = 'ORDER00994';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00995';
update "order" set client_name = 'Summit' where code = 'ORDER00996';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00504';
update "order" set client_name = 'Fox Esprit' where code = 'ORDER00990';
update "order" set client_name = 'Fremantle' where code = 'ORDER00991';
update "order" set client_name = 'Disney' where code = 'ORDER00992';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00993';
update "order" set client_name = 'Fremantle' where code = 'ORDER00503';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER01094';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00998';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00999';
update "order" set client_name = 'Fox Telefonica' where code = 'ORDER00502';
update "order" set client_name = 'Fremantle' where code = 'ORDER00501';
update "order" set client_name = 'Scripps Network' where code = 'ORDER00672';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00052';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00506';
update "order" set client_name = 'Fremantle' where code = 'ORDER01056';
update "order" set client_name = 'Fremantle' where code = 'ORDER01057';
update "order" set client_name = 'Fremantle' where code = 'ORDER00969';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01054';
update "order" set client_name = 'Summit' where code = 'ORDER00345';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER00344';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00347';
update "order" set client_name = 'Summit' where code = 'ORDER00346';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00468';
update "order" set client_name = 'Fox Esprit' where code = 'ORDER00469';
update "order" set client_name = 'Summit' where code = 'ORDER00343';
update "order" set client_name = 'Summit' where code = 'ORDER00342';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00464';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00465';
update "order" set client_name = 'Fremantle' where code = 'ORDER00466';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00467';
update "order" set client_name = 'FX' where code = 'ORDER00349';
update "order" set client_name = 'Lionsgate' where code = 'ORDER00461';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00462';
update "order" set client_name = 'Lionsgate' where code = 'ORDER00463';
update "order" set client_name = 'Fox Latin America' where code = 'ORDER00868';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00869';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER00299';
update "order" set client_name = 'Fremantle' where code = 'ORDER00860';
update "order" set client_name = 'Fremantle' where code = 'ORDER00861';
update "order" set client_name = 'Fox Esprit' where code = 'ORDER00862';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER00298';
update "order" set client_name = 'ESPN' where code = 'ORDER00864';
update "order" set client_name = 'Fox Latin America' where code = 'ORDER00865';
update "order" set client_name = 'Fox Latin America' where code = 'ORDER00866';
update "order" set client_name = 'Summit' where code = 'ORDER00867';
update "order" set client_name = 'Warner Brothers iTunes' where code = 'ORDER00903';
update "order" set client_name = 'Fremantle EST' where code = 'ORDER00902';
update "order" set client_name = 'Santa Monica Video' where code = 'ORDER00901';
update "order" set client_name = 'Santa Monica Video' where code = 'ORDER00900';
update "order" set client_name = 'Fremantle' where code = 'ORDER00907';
update "order" set client_name = 'Fox Esprit' where code = 'ORDER00696';
update "order" set client_name = 'Fremantle' where code = 'ORDER00905';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00904';
update "order" set client_name = 'Fremantle' where code = 'ORDER00909';
update "order" set client_name = 'Fremantle' where code = 'ORDER00908';
update "order" set client_name = 'DreamWorks' where code = 'ORDER01117';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER01039';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01115';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01114';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01113';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01112';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01111';
update "order" set client_name = 'Fremantle' where code = 'ORDER01110';
update "order" set client_name = 'Paramount' where code = 'ORDER00118';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01119';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01118';
update "order" set client_name = 'Indomina' where code = 'ORDER01067';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00534';
update "order" set client_name = 'Warner Brothers iTunes' where code = 'ORDER00891';
update "order" set client_name = 'Fox Playstation' where code = 'ORDER01066';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER00290';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01065';
update "order" set client_name = 'Fremantle' where code = 'ORDER01064';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01205';
update "order" set client_name = 'Summit' where code = 'ORDER01063';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER01062';
update "order" set client_name = 'ESPN' where code = 'ORDER00640';
update "order" set client_name = 'ESPN' where code = 'ORDER00641';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00769';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER00768';
update "order" set client_name = 'Fox Samsung' where code = 'ORDER00644';
update "order" set client_name = 'Fox Samsung' where code = 'ORDER00645';
update "order" set client_name = 'DreamWorks' where code = 'ORDER00646';
update "order" set client_name = 'DreamWorks' where code = 'ORDER00647';
update "order" set client_name = 'Lit Post' where code = 'ORDER00763';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00762';
update "order" set client_name = 'Lionsgate' where code = 'ORDER00162';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00766';
update "order" set client_name = 'Summit' where code = 'ORDER00765';
update "order" set client_name = 'Fremantle' where code = 'ORDER00764';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00927';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00796';
update "order" set client_name = 'Fremantle' where code = 'ORDER01209';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01208';
update "order" set client_name = 'Fremantle' where code = 'ORDER00245';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01203';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01202';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01201';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER01200';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01207';
update "order" set client_name = 'Fremantle' where code = 'ORDER00246';
update "order" set client_name = 'Strand Releasing' where code = 'ORDER01059';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER01087';
update "order" set client_name = 'Warner Brothers iTunes' where code = 'ORDER01162';
update "order" set client_name = 'Fremantle' where code = 'ORDER01163';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER01160';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00247';
update "order" set client_name = 'Fox Esprit' where code = 'ORDER01166';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01167';
update "order" set client_name = 'Fremantle EST' where code = 'ORDER01164';
update "order" set client_name = 'Santa Monica Video' where code = 'ORDER01165';
update "order" set client_name = 'Summit' where code = 'ORDER00240';
update "order" set client_name = 'Fremantle' where code = 'ORDER01168';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01169';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01047';
update "order" set client_name = 'Strand Releasing' where code = 'ORDER00793';
update "order" set client_name = '20th Century Fox' where code = 'ORDER01244';
update "order" set client_name = 'DirecTV' where code = 'ORDER00790';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00605';
update "order" set client_name = 'Fremantle SAN Duplication' where code = 'ORDER00243';
update "order" set client_name = 'Summit' where code = 'ORDER00499';
update "order" set client_name = 'Echostar' where code = 'ORDER00498';
update "order" set client_name = 'Fox Playstation' where code = 'ORDER00715';
update "order" set client_name = 'Echostar' where code = 'ORDER00495';
update "order" set client_name = 'Lionsgate' where code = 'ORDER00494';
update "order" set client_name = 'Echostar' where code = 'ORDER00497';
update "order" set client_name = 'Echostar' where code = 'ORDER00496';
update "order" set client_name = 'Fox Latin America' where code = 'ORDER00491';
update "order" set client_name = 'Fremantle EST' where code = 'ORDER00490';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00493';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER00492';
update "order" set client_name = 'Fox Xbox' where code = 'ORDER00169';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00168';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER01069';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER01068';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00165';
update "order" set client_name = 'ESPN' where code = 'ORDER00164';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00167';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00166';
update "order" set client_name = 'Paramount' where code = 'ORDER00161';
update "order" set client_name = 'Max Post' where code = 'ORDER00160';
update "order" set client_name = 'FX' where code = 'ORDER00163';
update "order" set client_name = 'Daniel Englehardt' where code = 'ORDER00244';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00797';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00794';
update "order" set client_name = 'A and E' where code = 'ORDER00795';
update "order" set client_name = 'Strand Releasing' where code = 'ORDER00792';
update "order" set client_name = 'Fox iTunes' where code = 'ORDER00241';
update "order" set client_name = 'Scripps Network' where code = 'ORDER00242';
update "order" set client_name = 'Lit Post' where code = 'ORDER00791';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00248';
update "order" set client_name = 'Warner Brothers' where code = 'ORDER00249';
update "order" set client_name = 'A and E' where code = 'ORDER00798';
update "order" set client_name = '20th Century Fox' where code = 'ORDER00799';
